---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kube-app
  labels:
    app: postgres-db
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: mypass
