---
apiVersion: v1
kind: Service
metadata:
  name: web-httpd-service
  namespace: kube-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: web-httpd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-httpd-deployment
  namespace: kube-app
spec:
  selector:
    matchLabels:
      app: web-httpd
  replicas: 3
  template:
    metadata:
      labels:
        app: web-httpd
    spec:
      containers:
        - name: web-httpd
          image: httpd:2.4.55
          ports:
            - containerPort: 80
